# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]

permissions:
  contents: write
  
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
       submodules: 'recursive'
  
    # - name: Prepare Vulkan SDK
    #   uses: humbletim/setup-vulkan-sdk@v1.2.1
    #   with:
    #    vulkan-query-version: 1.4.304.1
    #    vulkan-components: Vulkan-Headers, Vulkan-Loader
    #    vulkan-use-cache: true
       
    # --- STANDARD BUILD ---
    - name: Configure CMake (Standard)
      run: cmake -B ${{github.workspace}}/build-standard -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_MEDICORP=OFF

    - name: Build (Standard)
      run: cmake --build ${{github.workspace}}/build-standard --config ${{env.BUILD_TYPE}}

    - name: Test (Standard)
      working-directory: ${{github.workspace}}/build-standard
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Package (Standard)
      working-directory: ${{github.workspace}}/build-standard
      run: cmake --build . --target package --config ${{env.BUILD_TYPE}}

    - name: Rename Standard Package
      shell: pwsh
      run: |
        Set-Location build-standard
        Get-ChildItem -Filter *.zip | ForEach-Object {
          Rename-Item $_.FullName "EDVoice-Standard-${{env.BUILD_TYPE}}.zip"
        }

    # --- MEDICORP BUILD ---
    - name: Configure CMake (MediCorp)
      run: cmake -B ${{github.workspace}}/build-medicorp -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_MEDICORP=ON

    - name: Build (MediCorp)
      run: cmake --build ${{github.workspace}}/build-medicorp --config ${{env.BUILD_TYPE}}

    - name: Test (MediCorp)
      working-directory: ${{github.workspace}}/build-medicorp
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Package (MediCorp)
      working-directory: ${{github.workspace}}/build-medicorp
      run: cmake --build . --target package --config ${{env.BUILD_TYPE}}

    - name: Rename MediCorp Package
      shell: pwsh
      run: |
        Set-Location build-medicorp
        Get-ChildItem -Filter *.zip | ForEach-Object {
          Rename-Item $_.FullName "EDVoice-MediCorp-${{env.BUILD_TYPE}}.zip"
        }

    # --- UPLOAD TO RELEASE ---
    - name: Upload Release Assets
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{github.workspace}}/build-standard/EDVoice-Standard-${{env.BUILD_TYPE}}.zip
          ${{github.workspace}}/build-medicorp/EDVoice-MediCorp-${{env.BUILD_TYPE}}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_UPDATE_RELEASE }}
